### ISSUE TITLE
公众号的所有放到一个房间

### ISSUE THREAD

**Issue by Kerwin1202** [duo/matrix-wechat#11]
希望可以支持公众号的所有放到一个房间 

订阅号比较多 几百个，每天都有更新，能否吧他们放到一个房间里而非单独每个联系人，容易在联系人处把其他人消息刷掉

如果放到一个房间里 这样我只需要关注所有qq/微信这一屏幕就好了，不用切换，不然一会没看消息，联系人处只能显示8个被刷没了。

至于对公众号的发消息以及接受回复可以采用 @这个人 +消息去发送 回来的消息就放到房间里

当然，如果方便可以开个配置 把配置的单独放出来（这种算特别关注）

<img width="328" alt="image" src="https://user-images.githubusercontent.com/16319833/210121430-7963bd63-ce1b-41f7-8adf-eff97b1e0ae2.png">

**Comment by duo** [comment]
对于这种把同一类归档的需求, 在 matrix 这边可以考虑利用 `space` 这个功能, 比如你在客户端新建一个公众号的 space,  然后把订阅号都加进去, 这样就不会和默认的 home space (主页) 混一起了

然后联系人不仅仅能显示 8 个的呐, 下面那个 `多显示 xxx 个` 点一下就好

至于添加归档到同一个房间的支持, 这个改动还蛮大的, 相当于破坏了目前的一对一的映射, 暂时没有想到比较自然点的抽象去支持

**Comment by Kerwin1202** [comment]
space 这个功能确实可以归类，但是归类完还是会显示在home 里。

我其实就希望在 home 的 space 里 显示所有的最新联系人以及房间的活动的消息，这样我在不去切换左侧的 space  情况下看到所有未读消息

（因为我切换到别的 space 里就可能遗漏或延迟看到其他space的最新消息  其实就用原来多个平台也是一个道理切 qq 就还需要切微信才可以看到消息，用matrix 的目的就是为了不切换（左侧space 也不想切

至于你说的联系人下面 `多显示xxx` 的确可以  但是呢，比如 500个 点一次 会显示200个，然后不能很快再点一次缩回来，因为点击多显示 列表变长了没任何消息 此时就需要立马缩回来， 但是目前得滚动到底部才看到按扭，而且这个按扭还是显示 `多显示`  因为第一次点击是只显示了 一部分比如（200个）它得全部显示才有 `显示更少` 按扭

**Comment by duo** [comment]
我这用的 SchildiChat 客户端是支持的, 那看来是 Element 的行为是归类完还继续显示在 home 了么...

暂时想到的一个暴力的方法是定制 [matrix-wechat-agent](https://github.com/Kerwin1202/matrix-wechat-agent)

类似 [appservice.go#L272](https://github.com/Kerwin1202/matrix-wechat-agent/blob/master/internal/appservice.go#L272) 这里的逻辑对公众号的消息改成某个虚拟的 `xxxx@chatroom` 群消息
然后在 [wechatclient.go](https://github.com/Kerwin1202/matrix-wechat-agent/blob/master/internal/wechatclient.go) 针对这个虚拟群的 GetGroupInfo/GetGroupMembers/GetGroupMemberNickname/GetGroupList 做特殊处理...

如果还希望能回复的话, 还得再改多些...

**Comment by Kerwin1202** [comment]
我安装了个  SchildiChat 但是好像是一样的？ 

公众号 是这么加的2个房间  但是还是出现在了 home 里。对比 Element 是分开的联系人和房间，SchildiChat 只有一个列表，也还可以接受，毕竟稍微滚动下就可以了

<img width="305" alt="image" src="https://user-images.githubusercontent.com/16319833/210161316-c976bb13-b14d-43b5-acbd-d75f3dac4e8c.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/16319833/210161308-46d30d2c-8ec3-41be-820e-29d37052f01f.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/16319833/210161310-141f46bc-20a1-49cb-92f8-d632720fd92b.png">


至于定制的话，确实提 issue 之前是想自己改得，但是对 go 不熟，所以没下手，所以来问了。。
我晚点有空也尝试看看，有问题再来问你 

另外的话想问一个这个问题 我在 [appservice.go#L272](https://github.com/Kerwin1202/matrix-wechat-agent/blob/829571eb5bf3088f748fcd13735d82fa2b89f399/internal/appservice.go#L272)  加了一段代吗（未提交只是定位） 就是用来转发某个群到另一个群 用的以下代码


```
if msg.Sender == "xxxx@chatroom" {
		GetWechatManager().ForwardMessage("@xxx:xxx", "xxx@chatroom", msg.MsgID)

               # 这里可以转发消息，但是 自己这个 room 收不到，所以加了以下代码给自己发一次 但是一直无法收到

		event1 := &WebsocketEventReqeust{
			MXID:      mxid,
			ID:        msg.MsgID,
			Timestamp: ts,
			Target:    "xxxx@chatroom",
			EventType: EventText,
			Content:   msg.Message,
		}
		as.wsWriteLock.Lock()
		log.Debugf("Sending evnet %+v", event1)
		err := ws.WriteJSON(&event1)
		as.wsWriteLock.Unlock()
		if err != nil {
			log.Warnf("Failed to send event %d: %v", msg.MsgID, err)
		}
	}
```

**Comment by duo** [comment]
room 收不到这种没遇到过, 感觉只能通过 matrix-wechat 和 homeserver 的日志来排查了

**Comment by Kerwin1202** [comment]
先关了，SchildiChat 开启这个设置能用

<img width="551" alt="image" src="https://user-images.githubusercontent.com/16319833/211179581-badb569d-fe7c-4774-813a-1ca38e9a21c1.png">
