### ISSUE TITLE
Sync messages sent from WeChat

### ISSUE THREAD

**Issue by reekystive** [duo/matrix-wechat#16]
目前一切工作良好，但是还有一个问题：

从微信客户端（例如 iOS）发送的消息不会出现在 Matrix 的客户端中。

作者的 matrix-qq 没有这个问题，所以想问一下这种 hook 微信客户端的方式有办法获取自己发送的消息吗？

**Comment by duo** [comment]
我这没有问题呐, 目前应该只有在被 hook 的微信 Windows 客户端发出的消息会被过滤，而同用户的微信移动客户端的消息是会正常出现在 Matrix 里的

**Comment by reekystive** [comment]
啊，我用微信的 iOS 客户端，群聊的消息可以同步到 Matrix 里，但显示并不是自己发送的，私聊的消息就完全不会出现在 Matrix 里 🥲

**Comment by duo** [comment]
这种一般是 [double puppeting](https://duo.github.io/posts/matrix-qq-wechat/#shared-secret-authenticator) 没有开启的原因呐, bridge 日志里应该会提示 `user doesn't have double puppeting enabled` 之类的

**Comment by reekystive** [comment]
确实是这样，我把 [Shared Secret Authenticator](https://github.com/devture/matrix-synapse-shared-secret-auth) 这个 module 加上之后就正常了，Thanks~

**Comment by ajkessel** [comment]
Can anyone provide a tip in English for how to address this issue?

**Comment by duo** [comment]
> Can anyone provide a tip in English for how to address this issue?

FYI https://docs.mau.fi/bridges/general/double-puppeting.html

**Comment by ajkessel** [comment]
Thanks for the pointer -- I've tried all three methods there: using an access token, using shared secret, and using appservice. In all of them, I get the same error:
```

**Comment by ajkessel** [comment]
Figured it out. The problem was I was trying to IM myself, which is possible in both WeChat and Matrix, but doesn't puppet correctly (presumably some confusion about when you are sending messages to yourself).
