### ISSUE TITLE
更新docker hub的镜像

### ISSUE THREAD

**Issue by iaurman** [duo/matrix-wechat#2]
目前的docker不能直接使用，需要run之后替换matrix-wechat-agent.exe和ComWeChatRobot的文件，能否更新镜像，默认包括这些文件，感谢。

**Comment by duo** [comment]
镜像默认有这些文件的, 如果检测到 /home/user/matrix-wechat-agent/matrix-wechat-agent.exe 存在是不会用镜像里的进行替换

**Comment by iaurman** [comment]
> 镜像默认有这些文件的, 如果检测到 /home/user/matrix-wechat-agent/matrix-wechat-agent.exe 存在是不会用镜像里的进行替换

默认的这些文件无法使用，得下载最新的那些文件替换默认复制的那几个之后，才能正常工作

**Comment by duo** [comment]
docker 0.0.5 镜像在 ComWeChatRobot 更新到 3.7.0.30-0.0.8 才更新的, 目前应该没有更新的版本...

**Comment by iaurman** [comment]
奇怪了，有空我再试试吧，可能是我这边的问题
