### ISSUE TITLE
关于提及功能的问题

### ISSUE THREAD

**Issue by yunkuangao** [duo/matrix-wechat#20]
在wechat和qq中，新版的element似乎用的
`https://homeserver.org/#/user/@_wechat_wxid_uuid:homeserver.org`
而这种API好像不能在微信端识别为真正的@，而是显示为
`用户名称 (https://homeserver.org/#/user/@_wechat_wxid_uuid:homeserver.org)`

而如果是用旧版客户端的话，API是这种模式，可以在微信端正常at
`https://homeserver.org/#/@_wechat_wxid_uuid:homeserver.org`

**Comment by duo** [comment]
请问你的 Element 版本是?
目前用渲染的是 `https://matrix.to/#/@_wechat_wxid_uuid:homeserver.org` , 应该不会不兼容
虽然现在没有根据最新的文档设置 `m.mentions`, 但那个应该是只影响通知, 不会影响显示才对

Ref: https://spec.matrix.org/unstable/client-server-api/#user-and-room-mentions

**Comment by yunkuangao** [comment]
应该和版本无关，和实验室功能有关，我在家里的element desktop(1.11.43)就可以正常使用，办公的电脑(1.11.43)上就是这种，另外我的web端(1.11.41)也是这样`https://ele.yka.moe/`,后面我排查一下是哪个特性的问题

**Comment by yunkuangao** [comment]
> Ref: https://spec.matrix.org/unstable/client-server-api/#user-and-room-mentions

这个特性我没有启用，客户端上的启用按钮是灰色的，可能我的synapse没启用

**Comment by yunkuangao** [comment]
找到问题了
该问题由于permalink_prefix修改为自定义url造成，在 https://github.com/vector-im/element-web/issues/26002 有提及,暂时只能删除permalink_prefix来解决
