### ISSUE TITLE
关于撤回功能的建议

### ISSUE THREAD

**Issue by yunkuangao** [duo/matrix-wechat#21]
现在的撤回是在其原消息上做的一个回复（如果我没理解错的话），如果是一个很长的内容或者一次性撤回了很多内容，会导致整个面板都被撤回消息所占满，从而影响正常的消息，可以考虑删除消息本身或者以其他方式来提示比较好？

**Comment by duo** [comment]
可以把 `bridge.allow_redaction` 设置成 `true`

**Comment by yunkuangao** [comment]
好的，可以了
