### ISSUE TITLE
语音消息的通知

### ISSUE THREAD

**Issue by iaurman** [duo/matrix-wechat#4]
如题，微信电话没有消息通知
有时候手机静音在一旁，自己在电脑前，错过一堆微信电话

**Comment by iaurman** [comment]
matrix-qq同样没有

**Comment by duo** [comment]
这两个得分别依赖 [MiraiGo](https://github.com/Mrs4s/MiraiGo) 和 [ComWeChatRobot](https://github.com/ljc545w/ComWeChatRobot) 这两个库后续的支持情况了...

**Comment by duo** [comment]
95fa39c147a2300f9f2d2f357537ef1d3af59520 已经支持 VoIP 的通知了,  ComWechatRobot 需要更新到 [3.7.0.30-0.0.9-pre](https://github.com/ljc545w/ComWeChatRobot/releases/tag/3.7.0.30-0.0.9-pre), agent 也需要更新
