### ISSUE TITLE
[FR] 使用好友备注当作matrix联系人名称

### ISSUE THREAD

**Issue by iaurman** [duo/matrix-wechat#6]
默认是该好友的昵称，而不是好友备注
<img width="262" alt="image" src="https://user-images.githubusercontent.com/46162162/198347316-86537b09-7f4c-4a09-8881-f9ca1817982d.png">
![a](https://user-images.githubusercontent.com/46162162/198347841-73144867-3013-4365-8ec1-09d51b666895.jpg)
（还有群组中非好友的群聊昵称也没有利用到）

**Comment by duo** [comment]
设计上, 是可以多人登录自己的微信, 而备注这个信息是不一致的, 可能会出现同步的时候, 虚拟用户的名字反复横跳, 以及会暴露出自己给他人的备注
如果只自用的话, 那么在 ```config.yaml``` 修改 ```displayname_template: "{{if .Remark}}{{.Remark}}{{else if .Name}}{{.Name}}{{else}}{{.Uin}}{{end}}"```
