### ISSUE TITLE
Failed to log in: websocket not connected

### ISSUE THREAD

**Issue by heuzef** [duo/matrix-wechat#7]
Hi :)
Did you have an idea why my Wechat bridge bot say me that ?

![This is an image](https://matrix.heuzef.com/_matrix/media/r0/download/matrix.heuzef.com/oazCTQVoyQLtorrdmaOmiXOU)

**Comment by duo** [comment]
You need a [matrix-wechat-agent](https://github.com/duo/matrix-wechat-agent) running on windows (with wechat installed) or a [matrix-wechat-docker](https://github.com/duo/matrix-wechat-docker)

**Comment by heuzef** [comment]
Ok I see, if I use docker, I will need an container for each user?

**Comment by duo** [comment]
The current docker image can launch one wechat client only (crash when open multi instance....)
So if you want multi user support, run the agent on windows...

**Comment by heuzef** [comment]
Ok Thanks :)
Juste for sur, i need 1 bridge + 1 agent/user or i need 1 bridge + 1 agent / user (2 containers for each user) ?

**Comment by duo** [comment]
The bridge just support one agent only...
So bridge + agent (on docker) for one user, bridge + agent (on windows) for multi user...

**Comment by heuzef** [comment]
Ok thanks :)
I thinks Windows it's not an elegant solution because it needs to be active all the time ... So i will try with a custom config with  multiple docker.

谢谢你
